banner:
  location: banner.txt

rest:
  request:
    header: API_USER_SERVER
      version: 1.0.0

server:
  port: 8443
  servlet:
    context-path: /api-user-server
  ssl:
    key-store: classpath:cbaeneprojects.pfx
    key-store-password: ${SSL_PASSWORD}
    keyStoreType: PKCS12

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
config:
  swagger:
    title: API (api-user)
    description: This contract have the specifications of the api-user methods
    terms: https://google.com
    licence: apache 2.0
    licenceUrl: https://google.com
    version: 1.0
    contact:
      name: API USER
      url: https://api-user.cbaeneprojects.com/
      email: cmverab@ufpso.edu.co
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: appsusers
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${BD_URL}
    username: ${BD_USER}
    password: ${BD_PASSWORD}